web:
  build: .
  restart: always
  env_file: ./.env
  volumes:
    - .:/app
web_migrate:
  extends:
    service: web
  command: python manage.py migrate
web_run:
  extends:
    service: web
  command: gunicorn cloudblue.wsgi:application --bind 0.0.0.0:8000
  ports:
    - "8000:8000"
  env_file:
    - ./.env
