# Generated by Django 3.2 on 2021-06-12 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210610_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'пользователь'), ('accepted', 'модератор'), ('failed', 'администратор')], default='new', max_length=12, verbose_name='Status'),
        ),
    ]
